### ISSUE TITLE
Function Connect-Graph is missing the "graph"

### ISSUE THREAD

**Issue by bwya77** [dustindortch/xMSGraph.PowerShell#1]
line 17 on the module

**Comment by dustindortch** [comment]
This is by design.  The PowerShell definition file has a prefix of "Graph" that makes the command `Connect-Graph` when loaded.

**Comment by dustindortch** [comment]
I have made a commit to change this.  I talked it over with a few people and it seems like a thing to add to support my principle of keeping code readable.  So, no more default prefix and each function has the full intended name.
